general.import = [
  "~/.config/alacritty/alacritt-theme/themes/rose_pine.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 10

decorations = "Buttonless"

opacity = 0.95
# blur = true

# startup_mode = "Fullscreen"

# option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Thin"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.style = "Thin"
size = 11.5
